# Generated by Django 3.0.5 on 2020-04-24 02:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='image',
            field=models.ImageField(upload_to=core.models.portada_custom_upload_to, verbose_name='Imagen'),
        ),
    ]
