# Generated by Django 3.0.5 on 2020-04-24 15:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200423_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bot App', max_length=160)),
                ('bot_application_url', models.URLField(blank=True, help_text='Coloca sólo el endpoint', null=True, verbose_name='URL del bot')),
                ('vertical_position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=15, verbose_name='Posición vertical')),
                ('horizontal_position', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=15, verbose_name='Posición Horizontal')),
                ('button_icon', models.ImageField(help_text='Formatos ico, jpg, png o gif. Relación de aspecto 1:1', upload_to=core.models.bot_custom_upload_to, verbose_name='Ícono')),
                ('width', models.IntegerField(default=350, verbose_name='Ancho')),
                ('height', models.IntegerField(default=500, verbose_name='Alto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Application',
                'verbose_name_plural': 'Bot Application',
            },
        ),
    ]
