# Generated by Django 3.0.5 on 2020-04-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botaplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botaplication',
            options={'verbose_name': 'Bot', 'verbose_name_plural': 'Bot'},
        ),
    ]
