# Generated by Django 3.0.5 on 2020-04-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200424_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botaplication',
            old_name='bot_application_url',
            new_name='endpoint',
        ),
    ]
