# Generated by Django 3.0.5 on 2020-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200424_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaplication',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Activado'),
        ),
    ]
