# Generated by Django 3.0.5 on 2020-04-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_botaplication_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botaplication',
            old_name='enabled',
            new_name='is_enabled',
        ),
    ]
