# Generated by Django 3.0.5 on 2020-04-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200424_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botaplication',
            name='is_enabled',
        ),
    ]
