# Generated by Django 3.0.5 on 2020-04-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_botaplication_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botaplication',
            old_name='title',
            new_name='name',
        ),
    ]
