# Generated by Django 3.0.5 on 2020-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200424_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botaplication',
            name='button_size',
            field=models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (50, 50)], default=20, verbose_name='Tamaño del ícono'),
        ),
    ]
