# Generated by Django 3.0.5 on 2020-04-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200424_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botaplication',
            name='endpoint',
            field=models.URLField(default='https://google.com', help_text='Coloca sólo el endpoint', verbose_name='URL del bot'),
            preserve_default=False,
        ),
    ]
